variables:
  # Specify the code example version. This version is used for tagging the staging repository.
  CE_REL_VERSION: 1.0.0

  # Specify the toolchain, separated by spaces. E.g. GCC_ARM IAR ARM
  CE_TOOLCHAIN_LIST: GCC_ARM IAR ARM

  # Specify the build configuration, separated by spaces. E.g. Release Debug
  CE_CONFIG_LIST: Release Debug

  # Specify the supported targets, separated by spaces. E.g. CY8CPROTO-062-4343W CY8CKIT-062-WIFI-BT CY8CKIT-062S2-43012
  CE_TARGET_LIST: CY8CKIT-062S2-43012 CY8CEVAL-062S2-LAI-4373M2 CY8CEVAL-062S2-MUR-43439M2

  # Specify the additional build parameters, like verbose output. Leave it empty if not needed.
  CE_BUILD_PARAM: ""

  # Specify the ModusToolbox version using which this CE will be tested by the CI script. When the value is empty, the script will use the latest version of the tool.
  MTB_INSTALL_VER: ""

  # Specify the Secure Boot policy (.json file name) only if you want to override the default policy.
  CE_SECURE_POLICY: ""

### DO NOT EDIT THE SECTIONS BELOW ###

include:
  - project: "wpp/ce/ci"
    ref: develop
    file: '/templates/yaml/mtb-example-default.yml'
