name: Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-20.04
    container:
      image: srikanthds/modustoolbox-container

    steps:
    - uses: actions/checkout@v3

    - name: Build App
      run: python3 -u app.py
